format_version: v1.0
type: UniqueComponent
attributes: {id: qspi}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: QSPI_BAUD_RATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '64000000'}
      - type: User
        attributes: {value: '25000000'}
  - type: KeyValueSet
    attributes: {id: QSPI_CPOL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '0'}
  - type: Integer
    attributes: {id: QSPI_SCBR}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: qspi, value: '1'}
- type: ElementPosition
  attributes: {x: '170', y: '60', id: qspi}
