format_version: v1.0
type: UniqueComponent
attributes: {id: core}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: BSP_PIN_16_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_17_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_18_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_20_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_21_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_22_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_23_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_24_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_25_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_29_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: TC1_WO0 (out)}
  - type: String
    attributes: {id: BSP_PIN_29_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_31_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: TC0_WO1 (out)}
  - type: String
    attributes: {id: BSP_PIN_31_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_32_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_33_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_34_FUNCTION_TYPE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: TC2_WO1 (out)}
  - type: String
    attributes: {id: BSP_PIN_34_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_35_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: String
    attributes: {id: BSP_PIN_3_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: DIGITAL}
  - type: Hex
    attributes: {id: CFGPCLKGEN4_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '2457'}
  - type: KeyValueSet
    attributes: {id: COMPILER_CHOICE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Combo
    attributes: {id: CONFIG_POSCMOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: HS}
  - type: KeyValueSet
    attributes: {id: DEVICE_TCM_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0'}
  - type: Boolean
    attributes: {id: GCLK_ID_24_CHEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: GCLK_ID_24_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: KeyValueSet
    attributes: {id: GCLK_ID_24_GENSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1'}
  - type: Boolean
    attributes: {id: GCLK_ID_25_CHEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: GCLK_ID_25_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: KeyValueSet
    attributes: {id: GCLK_ID_25_GENSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1'}
  - type: Boolean
    attributes: {id: GCLK_ID_26_CHEN}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: GCLK_ID_26_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: KeyValueSet
    attributes: {id: GCLK_ID_26_GENSEL}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '1'}
  - type: String
    attributes: {id: KEIL_STACK_HEAP_SIZE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '0x1200'}
  - type: Boolean
    attributes: {id: NVIC_17_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: NVIC_17_0_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: TC0_Handler}
  - type: Boolean
    attributes: {id: NVIC_17_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: NVIC_18_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: NVIC_18_0_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: TC1_Handler}
  - type: Boolean
    attributes: {id: NVIC_18_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Boolean
    attributes: {id: NVIC_19_0_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: String
    attributes: {id: NVIC_19_0_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: TC2_Handler}
  - type: Boolean
    attributes: {id: NVIC_19_0_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'false'}
  - type: Combo
    attributes: {id: OSCCON_NOSC_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: SPLL}
  - type: Hex
    attributes: {id: OSCCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '2097415'}
  - type: Hex
    attributes: {id: PMD3_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '32655'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_FUNCTION_0}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '44'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_FUNCTION_1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '43'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_FUNCTION_2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_PIN_0}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: RPB2G4R, value: RPB2G4R, key: RPB2}
          - type: Pair
            attributes: {description: RPB3G4R, value: RPB3G4R, key: RPB3}
          - type: Pair
            attributes: {description: RPB0G2R, value: RPB0G2R, key: RPB0}
          - type: Pair
            attributes: {description: RPA10G4R, value: RPA10G4R, key: RPA10}
          - type: Pair
            attributes: {description: RPB1G3R, value: RPB1G3R, key: RPB1}
          - type: Pair
            attributes: {description: RPB10G4R, value: RPB10G4R, key: RPB10}
          - type: Pair
            attributes: {description: RPB11G4R, value: RPB11G4R, key: RPB11}
          - type: Pair
            attributes: {description: RPB12G2R, value: RPB12G2R, key: RPB12}
          - type: Pair
            attributes: {description: RPA13G4R, value: RPA13G4R, key: RPA13}
          - type: Pair
            attributes: {description: RPB13G3R, value: RPB13G3R, key: RPB13}
          - type: Pair
            attributes: {description: RPA14G4R, value: RPA14G4R, key: RPA14}
          - type: Pair
            attributes: {description: RPB8G2R, value: RPB8G2R, key: RPB8}
          - type: Pair
            attributes: {description: RPB9G3R, value: RPB9G3R, key: RPB9}
          - type: Pair
            attributes: {description: RPB6G3R, value: RPB6G3R, key: RPB6}
          - type: Pair
            attributes: {description: RPB7G4R, value: RPB7G4R, key: RPB7}
          - type: Pair
            attributes: {description: RPB4G2R, value: RPB4G2R, key: RPB4}
          - type: Pair
            attributes: {description: RPB5G2R, value: RPB5G2R, key: RPB5}
          - type: Pair
            attributes: {description: RPA1G4R, value: RPA1G4R, key: RPA1}
          - type: Pair
            attributes: {description: RPA2G4R, value: RPA2G4R, key: RPA2}
          - type: Pair
            attributes: {description: RPA0G3R, value: RPA0G3R, key: RPA0}
          - type: Pair
            attributes: {description: RPA9G4R, value: RPA9G4R, key: RPA9}
          - type: Pair
            attributes: {description: RPA7G2R, value: RPA7G2R, key: RPA7}
          - type: Pair
            attributes: {description: RPA8G4R, value: RPA8G4R, key: RPA8}
          - type: Pair
            attributes: {description: RPA5G4R, value: RPA5G4R, key: RPA5}
          - type: Pair
            attributes: {description: RPA6G4R, value: RPA6G4R, key: RPA6}
          - type: Pair
            attributes: {description: RPA3G3R, value: RPA3G3R, key: RPA3}
          - type: Pair
            attributes: {description: RPA4G4R, value: RPA4G4R, key: RPA4}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '21'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_PIN_1}
    children:
    - type: Attributes
      children:
      - type: KeyValuePairList
        attributes: {id: pairs}
        children:
        - type: Pairs
          children:
          - type: Pair
            attributes: {description: RPB2G4R, value: RPB2G4R, key: RPB2}
          - type: Pair
            attributes: {description: RPB3G4R, value: RPB3G4R, key: RPB3}
          - type: Pair
            attributes: {description: RPB0G2R, value: RPB0G2R, key: RPB0}
          - type: Pair
            attributes: {description: RPA10G4R, value: RPA10G4R, key: RPA10}
          - type: Pair
            attributes: {description: RPB1G3R, value: RPB1G3R, key: RPB1}
          - type: Pair
            attributes: {description: RPB10G4R, value: RPB10G4R, key: RPB10}
          - type: Pair
            attributes: {description: RPB11G4R, value: RPB11G4R, key: RPB11}
          - type: Pair
            attributes: {description: RPB12G2R, value: RPB12G2R, key: RPB12}
          - type: Pair
            attributes: {description: RPA13G4R, value: RPA13G4R, key: RPA13}
          - type: Pair
            attributes: {description: RPB13G3R, value: RPB13G3R, key: RPB13}
          - type: Pair
            attributes: {description: RPA14G4R, value: RPA14G4R, key: RPA14}
          - type: Pair
            attributes: {description: RPB8G2R, value: RPB8G2R, key: RPB8}
          - type: Pair
            attributes: {description: RPB9G3R, value: RPB9G3R, key: RPB9}
          - type: Pair
            attributes: {description: RPB6G3R, value: RPB6G3R, key: RPB6}
          - type: Pair
            attributes: {description: RPB7G4R, value: RPB7G4R, key: RPB7}
          - type: Pair
            attributes: {description: RPB4G2R, value: RPB4G2R, key: RPB4}
          - type: Pair
            attributes: {description: RPB5G2R, value: RPB5G2R, key: RPB5}
          - type: Pair
            attributes: {description: RPA1G4R, value: RPA1G4R, key: RPA1}
          - type: Pair
            attributes: {description: RPA2G4R, value: RPA2G4R, key: RPA2}
          - type: Pair
            attributes: {description: RPA0G3R, value: RPA0G3R, key: RPA0}
          - type: Pair
            attributes: {description: RPA9G4R, value: RPA9G4R, key: RPA9}
          - type: Pair
            attributes: {description: RPA7G2R, value: RPA7G2R, key: RPA7}
          - type: Pair
            attributes: {description: RPA8G4R, value: RPA8G3R, key: RPA8}
          - type: Pair
            attributes: {description: RPA5G4R, value: RPA5G4R, key: RPA5}
          - type: Pair
            attributes: {description: RPA6G4R, value: RPA6G4R, key: RPA6}
          - type: Pair
            attributes: {description: RPA3G3R, value: RPA3G3R, key: RPA3}
          - type: Pair
            attributes: {description: RPA4G4R, value: RPA4G4R, key: RPA4}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '22'}
  - type: KeyValueSet
    attributes: {id: SYS_PORT_PPS_OUTPUT_PIN_2}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Boolean
    attributes: {id: TC0_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: TC0_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: Boolean
    attributes: {id: TC0_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Boolean
    attributes: {id: TC0_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: TC0_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: TC0_Handler}
  - type: Boolean
    attributes: {id: TC0_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc0, value: 'false'}
  - type: Boolean
    attributes: {id: TC1_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: TC1_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: Boolean
    attributes: {id: TC1_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: 'false'}
  - type: Boolean
    attributes: {id: TC1_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: TC1_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: TC1_Handler}
  - type: Boolean
    attributes: {id: TC1_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc1, value: 'false'}
  - type: Boolean
    attributes: {id: TC2_CLOCK_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: Integer
    attributes: {id: TC2_CLOCK_FREQUENCY}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: '64000000'}
  - type: Boolean
    attributes: {id: TC2_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: 'false'}
  - type: Boolean
    attributes: {id: TC2_INTERRUPT_ENABLE_UPDATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: core, value: 'true'}
  - type: String
    attributes: {id: TC2_INTERRUPT_HANDLER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: TC2_Handler}
  - type: Boolean
    attributes: {id: TC2_INTERRUPT_HANDLER_LOCK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tc2, value: 'false'}
  - type: Boolean
    attributes: {id: USE_PPS_OUTPUT_0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: USE_PPS_OUTPUT_1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: USE_PPS_OUTPUT_2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '400', y: '20', id: core}
