configName: wbz351_curiosity
folderName: wbz351_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..\..
processor: WBZ351
projectName: usart_ring_buffer_interrupt_wbz351_curiosity
settings:
  PackageFilter: bsp;core;csp;dev_packs;quick_docs
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CX-BZ3_DFP\1.0.21\WBZ35\atdf\WBZ351.atdf
