configName: wbz351_curiosity
folderName: wbz351_curiosity
format_version: v1.0
frameworkPath: ..\..\..\..\..
processor: WBZ351
projectName: ac_sleepwalk_singleshot_wbz351_curiosity
settings:
  PackageFilter: bootloader;bootloader_apps_pic32cm_le_ls;bsp;core;csp;Devices;dev_packs;harmony-services;quick_docs;wireless;wireless_wifi
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32CX-BZ3_DFP\1.0.30\WBZ35\atdf\WBZ351.atdf
